version: '3.8'

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    networks:
      - app-network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
